# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

f <- function(x) {
    .Call('_StatComp20021_f', PACKAGE = 'StatComp20021', x)
}

#' @title A  random walk Metropolis sampler using Rcpp
#' @description A random walk Metropolis sampler using Rcpp
#' @param sigma the variance of the normal distribution
#' @param x0 the initial value
#' @param N the number of points
#' @return a random sample of size \code{n}
#' @export
rwMetropolis <- function(sigma, x0, N) {
    .Call('_StatComp20021_rwMetropolis', PACKAGE = 'StatComp20021', sigma, x0, N)
}

